name: work
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: nsetup
        run: make setup
      - name: ntest
        run: make test
      - name: nlint
        run: make lint